export const articles = [
    {
        lightBg:false,
        topLine:"PROGRAMMING ARTICLES",
        heading:"What is React",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien",
        buttonLabel:"Read More",
        imgStart:false,
        img:require("../../Images/svg1.svg").default,
        imgInside:"Images/react-2.png",
        alt:"img",
        dark:true,
        primary:true,
        time: "August 19, 2022",
        writer: "Fatemeh Badiei",
        type: "Educational",
        numberComment : "33 Comments",
        allDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien."
    },
    {
        lightBg:true,
        topLine:"PROGRAMMING ARTICLES",
        heading:"How to become a Hacker",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien",
        buttonLabel:"Read More",
        imgStart:true,
        img:require("../../Images/svg2.svg").default,
        imgInside:"Images/hacker.jpg",
        alt:"img",
        dark:false,
        primary:false,
        time: "April 10, 2021",
        writer: "Fatemeh Badiei",
        type: "Educational",
        numberComment : "73 Comments",
        allDescription : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien."
    },
    {
        lightBg:false,
        topLine:"PROGRAMMING ARTICLES",
        heading:"Artificial Intelligence and Robots",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien",
        buttonLabel:"Read More",
        imgStart:false,
        img:require("../../Images/svg3.svg").default,
        imgInside:"Images/robot.jpg",
        alt:"img",
        dark:true,
        primary:true,
        time: "AFebruary 28, 2020",
        writer: "Fatemeh Badiei",
        type: "Educational",
        numberComment : "25 Comments",
        allDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien."
    },
    {
        lightBg:true,
        topLine:"PROGRAMMING ARTICLES",
        heading:"How to solve Bugs",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien",
        buttonLabel:"Read More",
        imgStart:true,
        img:require("../../Images/svg4.svg").default,
        imgInside:"Images/bug.jpg",
        alt:"img",
        dark:false,
        primary:false,
        time: "June 19, 2022",
        writer: "Fatemeh Badiei",
        type: "Educational",
        numberComment : "16 Comments",
        allDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien."
    },
    {
        lightBg:false,
        topLine:"PROGRAMMING ARTICLES",
        heading:"How to create a Mobile App",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien",
        buttonLabel:"Read More",
        imgStart:false,
        img:require("../../Images/svg5.svg").default,
        imgInside:"Images/mobile.jpg",
        alt:"img",
        dark:true,
        primary:true,
        time: "July 8, 2019",
        writer: "Fatemeh Badiei",
        type: "Educational",
        numberComment : "42 Comments",
        allDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien. Aenean vitae vehicula sapien Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare imperdiet turpis. Ut sollicitudin et nibh nec tincidunt. Fusce arcu enim, porttitor id dui in, lacinia pharetra nunc. Nulla bibendum nibh ex, in aliquet mauris rhoncus quis. Vestibulum at fringilla dui. Quisque varius enim velit, non hendrerit risus tincidunt sit amet. Aenean vitae vehicula sapien."
    }
]
